### ISSUE TITLE
[FEAT] Dark Mode

### ISSUE THREAD

**Issue by medoix** [linuxserver/docker-bambustudio#5]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Bambu Studio supports Dark Mode but in this image that option is not available within the Prefernces menu. The setting can be seen in BambuStudio.conf as ```dark_color_mode``` but it always auto resets to 0 on start for some reason.

### Reason for change

The stock UI is so bright.

**Comment by yourjelly** [comment]
I would like to second this

**Comment by j0nnymoe** [comment]
Seems an upstream issue.
https://github.com/bambulab/BambuStudio/issues/3542

**Comment by yourjelly** [comment]
![image](https://github.com/linuxserver/docker-bambustudio/assets/26312697/3857492d-6625-4b02-9430-8ba68a1c8645)
That looks like we only need to locate where this environment variable is located and allow it to be set by the docker variables, but we arent installing via flatpack in the same way it seems

**Comment by thelamer** [comment]
There is now a `DARK_MODE` env var for this container, if you are upgrading you will need to remove the file `/config/.config/openbox/autostart` and restart the container for it to work.

**Comment by yourjelly** [comment]
> There is now a `DARK_MODE` env var for this container, if you are upgrading you will need to remove the file `/config/.config/openbox/autostart` and restart the container for it to work.

![image](https://github.com/user-attachments/assets/db7b8a64-7612-4cff-b5fd-20a3bd388568)
I set that, removed that file and restarted but to no effect

**Comment by yourjelly** [comment]
![image](https://github.com/user-attachments/assets/35924b9d-88c9-4535-9f2a-abaee12ff587)
Got it to work after manually flipping the "dark_color_mode" setting to 1 in BambuStudio.conf

**Comment by yourjelly** [comment]
![image](https://github.com/user-attachments/assets/14c7052e-3538-42ea-9c34-5b1528950eaa)
Got it to work after doing the above and manually toggling "dark_color_mode" to 1
